Add Integration Tests To Deployment Flow

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -13,6 +13,22 @@ on:
           default: "main"
           type: string
 
+  workflow_call:
+    inputs:
+      cluster_name:
+        description: "Name of the target cluster for integration test run"
+        required: true
+        type: string
+      branch_name:
+        description: "Name of integration tests repository branch to use"
+        required: false
+        default: "main"
+        type: string
+
+env:
+  CLUSTER_NAME: ${{ inputs.cluster_name || github.event.inputs.cluster_name }}
+  BRANCH_NAME: ${{ inputs.branch_name || github.event.inputs.branch_name }}
+
 permissions:
   id-token: write  # This is required for requesting the JWT
   contents: read  # This is required for actions/checkout
@@ -42,6 +58,7 @@ jobs:
            with:
              repository: 'ministryofjustice/container-platform-integration-tests'
              ref: ${{ inputs.branch_name }}
+             ref: ${{ env.BRANCH_NAME }}
 
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
@@ -68,9 +85,14 @@ jobs:
          - name: Check kube config
            run: |
             kubectl config current-context || true
+
          - name: Run integration tests
            run: |
-             cd ./test;  ginkgo -r -v --show-node-events --output-interceptor-mode=none --junit-report=report.xml -- -cluster=${{ needs.set-cluster-name.outputs.cluster_name }}
+             echo "Cluster from shell: $CLUSTER_NAME"
+             env | grep CLUSTER_NAME || echo "CLUSTER_NAME not found in env"
+             cd ./test
+             pwd
+             ginkgo -r -v --show-node-events --output-interceptor-mode=none --junit-report=report.xml -- -cluster=${{ needs.set-cluster-name.outputs.cluster_name }}
 
          - name: Upload test report
            uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
