Add debug to Run Integration Tests step
Added debugging information before running tests.

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -87,7 +87,11 @@ jobs:
 
          - name: Run integration tests
            run: |
-             cd ./test;  ginkgo -r -v --progress --output-interceptor-mode=none --junit-report=report.xml
+             echo "Cluster from shell: $CLUSTER_NAME"
+             env | grep CLUSTER_NAME || echo "CLUSTER_NAME not found in env"
+             cd ./test
+             pwd
+             ginkgo -r -v --progress --output-interceptor-mode=none --junit-report=report.xml
 
          - name: Upload test report
            uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
